name: Playwright Test
permissions:
  contents: read
  pages: write
  id-token: write
on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for running manually'
        required: false
        default: 'Manual test run'
  schedule:
    - cron: '0 9 * * *'

jobs:
  pw-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/configure-pages@v6
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: lts/*
        cache: npm
    - name: Restore Playwright snapshots
      uses: actions/cache/restore@v5
      with:
        path: tests/**/*-snapshots
        key: not-going-to-hit-this
        restore-keys: snapshots-
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium
    - name: Run Playwright tests
      continue-on-error: true
      env:
        GOOGLE_APP_PASSWORD: ${{ secrets.GOOGLE_APP_PASSWORD }}
      run: npx playwright test
    - uses: actions/upload-pages-artifact@v5
      with:
        path: playwright-report/
    - uses: actions/upload-artifact@v7
      with:
        name: playwright-report
        path: |
          **/*-snapshots/**
          test-results/
          playwright-report/
        retention-days: 30
    - uses: actions/deploy-pages@v5
  pw-update:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: lts/*
        cache: npm
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium
    - name: Run Playwright Update Snapshots
      run: npx playwright test --update-snapshots
    - name: Save Playwright snapshots
      uses: actions/cache/save@v5
      with:
        path: tests/**/*-snapshots
        key: snapshots-${{ github.run_id }}
